### ISSUE TITLE
AM Playing Up after Update 

### ISSUE THREAD

**Issue by thorrrr** [ivan-hc/AM#512]
Been using AM for a long time very good and solid app.
But today gave me a messge about need to remove and reinstall which i did via the code on the site.
Everything looks ok but if i try to update it spills issues 

 "AM" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:

 ◆ anytype 0.40.8
 ◆ joplin 2.14.20
 ◆ localsend 1.14.0

 All self-updatable programs are excluded
-----------------------------------------------------------------------------
 >> START OF ALL PROCESSES <<
-----------------------------------------------------------------------------
 ◆ JOPLIN is updated, 0 seconds elapsed!
 ◆ LOCALSEND is updated, 0 seconds elapsed!
 ◆ ANYTYPE is updated, 1 seconds elapsed!
-----------------------------------------------------------------------------
 Nothing to do here!
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
 Checking for changes of the installation scripts in the online database...
mkdir: cannot create directory ‘/opt/anytype/.am-installer’: Permission denied
 ◆ No installation script for anytype, downloading one...
mkdir: cannot create directory ‘/opt/anytype/.am-installer’: Permission denied
/opt/anytype/.am-installer/anytype: No such file or directory
 ◆ Changed https://github.com/ivan-hc/AM/blob/main/programs/x86_64/joplin
 ◆ Changed https://github.com/ivan-hc/AM/blob/main/programs/x86_64/localsend
-----------------------------------------------------------------------------
 Check for updates in modules...
-----------------------------------------------------------------------------
rm: cannot remove '/opt/am/x86_64-apps': Permission denied
/opt/am/modules/sync.am: line 12: /opt/am/list: Permission denied
/opt/am/modules/sync.am: line 17: /opt/am/list: Permission denied

chown: invalid group: ‘:sudo’ 6.6.3-1..

I am the only user and admin user  ???

**Comment by ivan-hc** [comment]
yes, some parts of code are changed trying to ad a security layout between privileged users and unprivileged ones.

We are trying to solve this siche a lot of problems are coming up between various distros.

**Comment by ivan-hc** [comment]
@thorrrr remove am
```
sudo /opt/am/remove
```
and then reinstall it. A new fix has been added right now

**Comment by thorrrr** [comment]
Still broke removed added back tried to install but still permission errors 


![image](https://github.com/ivan-hc/AM/assets/8170673/abb53c06-2ff4-4461-9df8-082733afb298)

**Comment by nazdridoy** [comment]
> Still broke removed added back tried to install but still permission errors
> 
> ![image](https://private-user-images.githubusercontent.com/8170673/326060893-abb53c06-2ff4-4461-9df8-082733afb298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTI4MDcsIm5iZiI6MTcxNDE1MjUwNywicGF0aCI6Ii84MTcwNjczLzMyNjA2MDg5My1hYmI1M2MwNi0yZmY0LTQ0NjEtOWRmOC0wODI3MzNhZmIyOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTcyODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzNDQxMzdiMzkwZDE3N2NkMDM4YTNkYTU2NDFlNTc5NDYwNjVlZTI3MWZjNTRiYmFmMTY4N2I5MjljYTkyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g31mPhru3VAIvFH8wa7XmcRbL6n3Ma3cSZPD2u9DbRs)

- uninstall am 
- remove any remainings of /opt/am
- remove previously downloaded INSTALL file....
- reinstall am

this should fix your problem

**Comment by nazdridoy** [comment]
fixed by #511

**Comment by thorrrr** [comment]
![image](https://github.com/ivan-hc/AM/assets/8170673/7792c3a6-feb8-4b9c-82cb-e1d5067c3da3)

**Comment by ivan-hc** [comment]
I'm sorry for the inconvenience, I suggest uninstalling and reinstalling.

I downgraded from version 6.6.3 to version 6.6.2 to solve this an other issues.

AM is still not ready for this feature. Sorry.

**Comment by ivan-hc** [comment]
have you removed/installed it again? Remember that you have to remove the INSTALL file from your $HOME

**Comment by thorrrr** [comment]
yes i did that

**Comment by ivan-hc** [comment]
I think that you should reinstall also the apps, since the new version have changed permissions in that directories.

After then, everything work as before.

**Comment by ivan-hc** [comment]
@thorrrr have you solved now?

**Comment by ivan-hc** [comment]
From what I see in your screenshot, all missing modules/updated modules are downloaded correctly, so its just a question of permissions.

Being this a new installation, you have all permissions in place out of the box, in /opt/am

However, being the other apps already installed when you had the nomore available 6.6.3 version, you have all permissions and ownership not where it should be.

The ways are two:
- remove/reinstall all the apps using AM
- use chown and chmod to reset ownership and permissions

and that is.

**Comment by thorrrr** [comment]
HI only had to remove anytype and re add all good now  :)
Cheers have a great weekend

**Comment by ivan-hc** [comment]
Thank you, and I'm still sorry for what happened. Bye
